#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#!/bin/bash

# Fetch the last commit hash
LAST_COMMIT_HASH=$(git rev-parse HEAD)

sed -i "s/<meta id=\"version-tag\" version=\"[^\"]*\" \/>/<meta id=\"version-tag\" version=\"$LAST_COMMIT_HASH\" \/>/g" public/index.template.html
