#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#!/bin/bash

# Fetch the last commit hash
LAST_COMMIT_HASH=$(git rev-parse HEAD)

# Replace the version tag in index.template.html with the last commit hash
sed -i "s/version-tag/$LAST_COMMIT_HASH/g" public/index.html