name: Update Version

on:
  push:
    branches:
      - main

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch last commit hash
        run: echo "::set-output name=commit_hash::$(git rev-parse HEAD)"

      - name: Replace version tag
        run: |
          COMMIT_HASH=$(cat $GITHUB_SHA)
          sed "s/{VERSION_TAG}/$COMMIT_HASH/g" index.template.html > temp_index.html

      - name: Copy updated index.html to public folder
        run: cp temp_index.html public/index.html

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add public/index.html
          git commit -m "Update version tag to $GITHUB_SHA"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
