name: Update Version

on:
  push:
    branches:
      - main # Change this to your main branch name if it's different

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get last commit hash
        id: get_hash
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: Update version tag in index.html
        run: |
          sed -i "s/<meta id=\"version-tag\" version=\"[0-9a-f]*\" \/>/<meta id=\"version-tag\" version=\"${{ steps.get_hash.outputs.hash }}\" \/>/" public/index.html

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Stage changes
        run: git add .

      - name: Commit changes
        run: git commit -m "Update version tag to latest commit hash [${{ steps.get_hash.outputs.hash }}]"

      - name: Push changes
        run: git push origin main # Change 'main' to your main branch name if it's different
