name: Update version tag

on:
  push:
    branches:
      - main

jobs:
  update-version-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch commit hash
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"
        id: fetch_commit_hash
      - name: Replace version tag
        run: sed -i "s/version-tag/${{ steps.fetch_commit_hash.outputs.commit_hash }}/g" public/index.html